[metadata]
format = { version = "1.1" }

[versions]
minecraft = "1.21.11"

# Mod Loaders & Wrapper
fabricLoader = "0.18.3"
fabricApi = "0.140.0+1.21.11"
neoforge = "21.11.0-beta"
architectury = "19.0.1"
architecturyPlugin = "3.4.162"
architecturyLoom = "1.13.463"

# CUI dependencies
worldedit = "7.3.14"
cuiProtocol = "4.0.2"
modmenu = "16.0.0-rc.1"
viafabricplus = "3.3.0"
viaversion = "5.0.5"

# Dev Dependencies (Workflow, Publish)
parchment = "2025.10.12"
indra = "3.1.3"
vineflower = "1.10.1"
shadow = "8.3.5"
spotless = "6.25.0"
jvmConflictResolution = "2.1.2"
versions = "0.51.0"
curseForgeGradle = "1.1.26"
publishGithubRelease = "0.1.0"
minotaur = "2.8.7"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# Mod Loaders
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge"}
architectury = { module = "dev.architectury:architectury", version.ref = "architectury" }

# CUI Dependencies
worldedit = { module = "com.sk89q.worldedit:worldedit-fabric-mc1.21", version.ref = "worldedit" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
viafabricplus-api = { module = "de.florianmichael:ViaFabricPlus", version.ref = "viafabricplus" }
viaversion = { module = "com.viaversion:viaversion-common", version.ref = "viaversion" }
cuiProtocol-common = { module = "org.enginehub.worldeditcui-protocol:worldeditcui-protocol-common-mc1.21.11", version.ref = "cuiProtocol"}
cuiProtocol-fabric = { module = "org.enginehub.worldeditcui-protocol:worldeditcui-protocol-fabric-mc1.21.11", version.ref = "cuiProtocol"}
cuiProtocol-neoforge = { module = "org.enginehub.worldeditcui-protocol:worldeditcui-protocol-neoforge-mc1.21.11", version.ref = "cuiProtocol"}

# Dev Dependencies
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.10", version.ref = "parchment" }

[plugins]
# From the Architectury Template
architectury-plugin = { id = "architectury-plugin", version.ref = "architecturyPlugin" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "architecturyLoom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

# Dev Workflow
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
indra-spotlessLicenser = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
jvmConflictResolution = { id = "org.gradlex.jvm-dependency-conflict-resolution", version.ref = "jvmConflictResolution" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
curseForgeGradle = { id = "net.darkhax.curseforgegradle", version.ref = "curseForgeGradle" }
publishGithubRelease = { id = "ca.stellardrift.publish-github-release", version.ref = "publishGithubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
